/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jFrame;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.MySQL2;

/**
 *
 * @author lakma
 */
public class IssueBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public IssueBook() {
        initComponents();
    }
    
    public void updateBookCount(){
        int bookId =  Integer.parseInt(jLabel8bookid.getText());
        try {
            MySQL2.executeIUD("UPDATE `book_details` SET `quantity` = `quantity` - '1'"
                            + "WHERE `book_id` = '" + bookId + "'");
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }

    public void getBookDetails() {
        int bookId = Integer.parseInt(txt_Bookid1.getText());

        try {
            ResultSet resultSet = MySQL2.executeSearch("SELECT * FROM `book_details` WHERE `book_id` ='" + bookId + "' ");

            if (resultSet.next()) {
                jLabel8bookid.setText(resultSet.getString("book_id"));
                jLabel10bookname.setText(resultSet.getString("book_name"));
                jLabel11authorname.setText(resultSet.getString("author"));
                jLabel12quantity.setText(resultSet.getString("quantity"));

            }else{
            jLabel12bookerror.setText("INVALID BOOK ID");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void getStudentDetails() {
        int studentId = Integer.parseInt(txt_Studentid.getText());

        try {
            ResultSet resultSet = MySQL2.executeSearch("SELECT * FROM `student_details`"
                    + "INNER JOIN `course` ON `course`.`id` = `student_details`.`course_id`"
                    + "INNER JOIN `branch` ON `branch`.`id` = `student_details`.`branch_id`"
                    + "INNER JOIN `student_status` ON `student_status`.`id` = `student_details`.`status_id` WHERE `student_id` ='" + studentId + "' ");

            if (resultSet.next()) {
                jLabel18studentid.setText(resultSet.getString("student_id"));
                jLabel19studentname.setText(resultSet.getString("student_name"));
                jLabel20course.setText(resultSet.getString("course.name"));
                jLabel13branch.setText(resultSet.getString("branch.name"));
                jLabel22status.setText(resultSet.getString("student_status.name"));

           }else{
            jLabel12studenterror.setText("INVALID STUDENT ID");
            }
            

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelissuebook = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8bookid = new javax.swing.JLabel();
        jLabel10bookname = new javax.swing.JLabel();
        jLabel11authorname = new javax.swing.JLabel();
        jLabel12quantity = new javax.swing.JLabel();
        jLabel12bookerror = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13branch = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18studentid = new javax.swing.JLabel();
        jLabel19studentname = new javax.swing.JLabel();
        jLabel20course = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22status = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12studenterror = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_Studentid = new app.bolivia.swing.JCTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_Bookid1 = new app.bolivia.swing.JCTextField();
        jLabel13 = new javax.swing.JLabel();
        issuedate = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        duedate = new com.toedter.calendar.JDateChooser();
        rSMaterialButtonCircle2 = new rojerusan.RSMaterialButtonCircle();
        rSMaterialButtonCircle3 = new rojerusan.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelissuebook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-book-50white.png"))); // NOI18N
        jLabel2.setText("BOOK DETAILS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 290, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 380, 8));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Book Id :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 80, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Book Name :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 120, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Author Name :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 130, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Quantity :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 90, -1));

        jLabel8bookid.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8bookid.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel8bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 280, 30));

        jLabel10bookname.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10bookname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel10bookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 240, 30));

        jLabel11authorname.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel11authorname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel11authorname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 240, 30));

        jLabel12quantity.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel12quantity.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel12quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 240, 30));

        jLabel12bookerror.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        jLabel12bookerror.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel12bookerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 380, 50));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-go-back.gif"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanelissuebook.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 910));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 380, 8));

        jLabel13branch.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel13branch.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jLabel13branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 240, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Student Id :");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 110, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Student Name :");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 140, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Grade :");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 80, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("School :");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 80, -1));

        jLabel18studentid.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel18studentid.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jLabel18studentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 230, 30));

        jLabel19studentname.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel19studentname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jLabel19studentname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 210, 30));

        jLabel20course.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel20course.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jLabel20course, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 290, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Status :");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 80, -1));

        jLabel22status.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel22status.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jLabel22status, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 240, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-student-50white.png"))); // NOI18N
        jLabel10.setText("STUDENT DETAILS");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 340, -1));

        jLabel12studenterror.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        jLabel12studenterror.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jLabel12studenterror, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 380, 50));

        jPanelissuebook.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 420, 910));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-book 2.gif"))); // NOI18N
        jLabel9.setText("Issue Book");
        jPanelissuebook.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 120, 340, -1));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanelissuebook.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 190, 520, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelissuebook.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 0, 50, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("ENTER STUDENT ID");
        jPanelissuebook.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 400, 190, 30));

        txt_Studentid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 51, 51)));
        txt_Studentid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_Studentid.setPlaceholder("Enter Student Id");
        txt_Studentid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_StudentidFocusLost(evt);
            }
        });
        txt_Studentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_StudentidActionPerformed(evt);
            }
        });
        jPanelissuebook.add(txt_Studentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 400, 290, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("BOOK ISSUE DATE");
        jPanelissuebook.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 500, 180, 30));

        txt_Bookid1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 51, 51)));
        txt_Bookid1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_Bookid1.setPlaceholder("Enter Book Id");
        txt_Bookid1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_Bookid1FocusLost(evt);
            }
        });
        txt_Bookid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Bookid1ActionPerformed(evt);
            }
        });
        jPanelissuebook.add(txt_Bookid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 300, 290, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setText("ENTER BOOK ID");
        jPanelissuebook.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 300, 160, 30));

        issuedate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        jPanelissuebook.add(issuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 500, 290, 30));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 51, 51));
        jLabel18.setText("DUE DATE");
        jPanelissuebook.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 590, 160, 30));

        duedate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        jPanelissuebook.add(duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 590, 290, 30));

        rSMaterialButtonCircle2.setBackground(new java.awt.Color(255, 51, 51));
        rSMaterialButtonCircle2.setText("ISSUE BOOK");
        rSMaterialButtonCircle2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        jPanelissuebook.add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 690, 490, 60));

        rSMaterialButtonCircle3.setBackground(new java.awt.Color(0, 0, 204));
        rSMaterialButtonCircle3.setText("CLEAR ALL");
        rSMaterialButtonCircle3.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        rSMaterialButtonCircle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle3ActionPerformed(evt);
            }
        });
        jPanelissuebook.add(rSMaterialButtonCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 790, 490, 60));

        getContentPane().add(jPanelissuebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 1030));

        setSize(new java.awt.Dimension(1540, 1032));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:

        HomePage homepage = new HomePage();
        homepage.setVisible(true);
        dispose();

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txt_StudentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_StudentidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_StudentidActionPerformed

    private void txt_Bookid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Bookid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Bookid1ActionPerformed

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
        //TODO add your handling code here:
        String book_id = txt_Bookid1.getText();
        String student_id = txt_Studentid.getText();
        //String quantity = jLabel12quantity.getText();
        Date issue_date = issuedate.getDate();
        Date due_date = duedate.getDate();

        if (book_id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter book id", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (student_id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter student id", "Warning", JOptionPane.WARNING_MESSAGE);

        } else {

            try {
                

                ResultSet resultSet = MySQL2.executeSearch("SELECT * FROM `issue_books`WHERE `issue_id`='" + student_id + "'");

                if (resultSet.next()) {
                    JOptionPane.showMessageDialog(this, " already book issued", "Warning", JOptionPane.WARNING_MESSAGE);
                } else {

                    Date date = new Date();
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

                    MySQL2.executeIUD("INSERT INTO `issue_books`(`book_details_book_id`,`student_details_student_id`,`issue_date`,`due_date`,`book_status_book_status_id`)"
                            + "VALUES('" + book_id + "','" + student_id + "','" + sdf.format(issue_date) + "','" + sdf.format(due_date) + "','1')");
                    
                    updateBookCount();



                    JOptionPane.showMessageDialog(this, "book issued successfully", "Warning", JOptionPane.WARNING_MESSAGE);
                    reset();
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    private void txt_Bookid1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Bookid1FocusLost
        // TODO add your handling code here:
        if (!txt_Bookid1.getText().equals("")) {
            getBookDetails();

        }
    }//GEN-LAST:event_txt_Bookid1FocusLost

    private void txt_StudentidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_StudentidFocusLost
        // TODO add your handling code here:
        if (!txt_Studentid.getText().equals("")) {
            getStudentDetails();

        }
    }//GEN-LAST:event_txt_StudentidFocusLost

    private void rSMaterialButtonCircle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle3ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_rSMaterialButtonCircle3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMacDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser duedate;
    private com.toedter.calendar.JDateChooser issuedate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel10bookname;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel11authorname;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel12bookerror;
    private javax.swing.JLabel jLabel12quantity;
    private javax.swing.JLabel jLabel12studenterror;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel13branch;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel18studentid;
    private javax.swing.JLabel jLabel19studentname;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20course;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22status;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8bookid;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelissuebook;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle3;
    private app.bolivia.swing.JCTextField txt_Bookid1;
    private app.bolivia.swing.JCTextField txt_Studentid;
    // End of variables declaration//GEN-END:variables

    private void reset() {
        txt_Bookid1.setText("");
        txt_Studentid.setText("");
        issuedate.setDate(null);
        duedate.setDate(null);
        jLabel8bookid.setText("");
        jLabel10bookname.setText("");
        jLabel11authorname.setText("");
        jLabel12quantity.setText("");
        jLabel18studentid.setText("");
        jLabel19studentname.setText("");
        jLabel20course.setText("");
        jLabel13branch.setText("");
        jLabel22status.setText("");
        jLabel12bookerror.setText("");
        jLabel12studenterror.setText("");

    }
}
