/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jFrame;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.MySQL2;

/**
 *
 * @author lakma
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public ReturnBook() {
        initComponents();
    }
    
    public void updateBookCount(){
        int bookId =  Integer.parseInt(txt_Bookid1.getText());
        try {
            MySQL2.executeIUD("UPDATE `book_details` SET `quantity` = `quantity` + '1'"
                            + "WHERE `book_id` = '" + bookId + "'");
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }

    public void getIssueBookDetails() {

        int bookId = Integer.parseInt(txt_Bookid1.getText());
        int studentId = Integer.parseInt(txt_Studentid.getText());

        try {
            ResultSet resultSet = MySQL2.executeSearch("SELECT * FROM `issue_books`"
                    + "INNER JOIN `book_details` ON `book_details`.`book_id` = `issue_books`.`book_details_book_id`"
                    + "INNER JOIN `student_details` ON `student_details`.`student_id` = `issue_books`.`student_details_student_id`"
                    + " WHERE `book_details_book_id` ='" + bookId + "' AND `student_details_student_id` ='" + studentId + "' ");

            if (resultSet.next()) {
                jLabel8issueid.setText(resultSet.getString("issue_books.issue_id"));
                jLabel10bookname.setText(resultSet.getString("book_details.book_name"));
                jLabel11studentname.setText(resultSet.getString("student_details.student_name"));
                jLabel12issuedate.setText(resultSet.getString("issue_books.issue_date"));
                jLabel7duedate.setText(resultSet.getString("issue_books.due_date"));

            } else {
                jLabel12bookerror.setText(" No Book Found ");

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelissuebook = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7duedate = new javax.swing.JLabel();
        jLabel8issueid = new javax.swing.JLabel();
        jLabel10bookname = new javax.swing.JLabel();
        jLabel11studentname = new javax.swing.JLabel();
        jLabel12issuedate = new javax.swing.JLabel();
        jLabel12bookerror = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_Studentid = new app.bolivia.swing.JCTextField();
        txt_Bookid1 = new app.bolivia.swing.JCTextField();
        jLabel13 = new javax.swing.JLabel();
        rSMaterialButtonCircle2 = new rojerusan.RSMaterialButtonCircle();
        rSMaterialButtonCircle3 = new rojerusan.RSMaterialButtonCircle();
        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rSMaterialButtonCircle4 = new rojerusan.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelissuebook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-book-50white.png"))); // NOI18N
        jLabel2.setText("ISSUED BOOK DETAILS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 380, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 380, 8));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Issue Id :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 80, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Book Name :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 120, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Student Name :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 150, -1));

        jLabel7duedate.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7duedate.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel7duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 680, 270, 30));

        jLabel8issueid.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8issueid.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel8issueid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 280, 30));

        jLabel10bookname.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10bookname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel10bookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 240, 30));

        jLabel11studentname.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel11studentname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel11studentname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 220, 30));

        jLabel12issuedate.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel12issuedate.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel12issuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 280, 30));

        jLabel12bookerror.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        jLabel12bookerror.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel12bookerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 380, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Issue Date :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 110, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Due Date :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 110, -1));

        jPanelissuebook.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 440, 1030));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-book 2.gif"))); // NOI18N
        jLabel9.setText("Return Book");
        jPanelissuebook.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 130, 210, -1));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanelissuebook.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 190, 380, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelissuebook.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 0, 50, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("STUDENT ID :");
        jPanelissuebook.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 410, 130, 30));

        txt_Studentid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 51, 51)));
        txt_Studentid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_Studentid.setPlaceholder("Enter Student Id");
        txt_Studentid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_StudentidFocusLost(evt);
            }
        });
        txt_Studentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_StudentidActionPerformed(evt);
            }
        });
        jPanelissuebook.add(txt_Studentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 400, 250, -1));

        txt_Bookid1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 51, 51)));
        txt_Bookid1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_Bookid1.setPlaceholder("Enter Book Id");
        txt_Bookid1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_Bookid1FocusLost(evt);
            }
        });
        txt_Bookid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Bookid1ActionPerformed(evt);
            }
        });
        jPanelissuebook.add(txt_Bookid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 300, 250, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setText("BOOK ID :");
        jPanelissuebook.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 310, 90, 30));

        rSMaterialButtonCircle2.setBackground(new java.awt.Color(102, 102, 255));
        rSMaterialButtonCircle2.setText("FIND DETAILS");
        rSMaterialButtonCircle2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        jPanelissuebook.add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 550, 390, 60));

        rSMaterialButtonCircle3.setBackground(new java.awt.Color(0, 102, 102));
        rSMaterialButtonCircle3.setText("CLEAR ALL");
        rSMaterialButtonCircle3.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        rSMaterialButtonCircle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle3ActionPerformed(evt);
            }
        });
        jPanelissuebook.add(rSMaterialButtonCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 710, 390, 60));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-go-back.gif"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/modern-library-with-vibrant-shelves-holding-numerous-books-illuminated-by-soft-blue-and-orange-lights-photo.jpg"))); // NOI18N
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 960));

        jPanelissuebook.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 1030));

        rSMaterialButtonCircle4.setBackground(new java.awt.Color(255, 51, 51));
        rSMaterialButtonCircle4.setText("RETURN BOOK");
        rSMaterialButtonCircle4.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        rSMaterialButtonCircle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle4ActionPerformed(evt);
            }
        });
        jPanelissuebook.add(rSMaterialButtonCircle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 630, 390, 60));

        getContentPane().add(jPanelissuebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 1030));

        setSize(new java.awt.Dimension(1540, 1031));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txt_StudentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_StudentidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_StudentidActionPerformed

    private void txt_Bookid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Bookid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Bookid1ActionPerformed

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
        //TODO add your handling code here:
        getIssueBookDetails();

    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    private void txt_Bookid1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Bookid1FocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_Bookid1FocusLost

    private void txt_StudentidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_StudentidFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_StudentidFocusLost

    private void rSMaterialButtonCircle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle3ActionPerformed
        // TODO add your handling code here:
        reset();

    }//GEN-LAST:event_rSMaterialButtonCircle3ActionPerformed

    private void rSMaterialButtonCircle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle4ActionPerformed
        // TODO add your handling code here:
        String book_id = txt_Bookid1.getText();
        String student_id = txt_Studentid.getText();
        

//        Date issue_date = jLabel12issuedate.getDate();
//        Date due_date = duedate.getDate();
        if (book_id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter book id", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (student_id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter student id", "Warning", JOptionPane.WARNING_MESSAGE);

        } else {

            try {

                ResultSet resultSet = MySQL2.executeSearch("SELECT * FROM `issue_books`WHERE `issue_id`='" + student_id + "'");

                if (resultSet.next()) {
                    JOptionPane.showMessageDialog(this, " Book Not Submited", "Warning", JOptionPane.WARNING_MESSAGE);
                } else {

//                    Date date = new Date();
//                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    MySQL2.executeIUD("UPDATE `issue_books` SET `book_status_book_status_id` = '2' WHERE `book_details_book_id` = '" + book_id + "' AND `student_details_student_id` = '" + student_id + "'");
                    
                    
                    updateBookCount();

//                    loadBookDetails();
                    JOptionPane.showMessageDialog(this, "Book Return successfully", "Warning", JOptionPane.WARNING_MESSAGE);
                    reset();
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_rSMaterialButtonCircle4ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:

        HomePage homepage = new HomePage();
        homepage.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMacDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel10bookname;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel11studentname;
    private javax.swing.JLabel jLabel12bookerror;
    private javax.swing.JLabel jLabel12issuedate;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7duedate;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel8issueid;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelissuebook;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle3;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle4;
    private app.bolivia.swing.JCTextField txt_Bookid1;
    private app.bolivia.swing.JCTextField txt_Studentid;
    // End of variables declaration//GEN-END:variables

    private void reset() {
        jLabel8issueid.setText("");
        jLabel10bookname.setText("");
        jLabel11studentname.setText("");
        jLabel12issuedate.setText("");
        jLabel7duedate.setText("");
        jLabel12bookerror.setText("");
        txt_Bookid1.setText("");
        txt_Studentid.setText("");
        
          }

}
